/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_moziqi_ndklearn_JniTest */

#ifndef _Included_com_moziqi_ndklearn_JniTest
#define _Included_com_moziqi_ndklearn_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_moziqi_ndklearn_JniTest
 * Method:    AddStr
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_moziqi_ndklearn_JniTest_AddStr
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_moziqi_ndklearn_JniTest
 * Method:    AddInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_moziqi_ndklearn_JniTest_AddInt
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_moziqi_ndklearn_JniTest
 * Method:    setArray
 * Signature: ([I[Ljava/lang/String;[F[D)I
 */
JNIEXPORT jint JNICALL Java_com_moziqi_ndklearn_JniTest_setArray
  (JNIEnv *, jclass, jintArray, jobjectArray, jfloatArray, jdoubleArray);

/*
 * Class:     com_moziqi_ndklearn_JniTest
 * Method:    setArrayObject
 * Signature: ([I[Ljava/lang/String;[F[D)I
 */
JNIEXPORT jint JNICALL Java_com_moziqi_ndklearn_JniTest_setArrayObject
  (JNIEnv *, jobject, jintArray, jobjectArray, jfloatArray, jdoubleArray);

/*
 * Class:     com_moziqi_ndklearn_JniTest
 * Method:    setObject
 * Signature: (Lcom/moziqi/ndklearn/Student;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_moziqi_ndklearn_JniTest_setObject
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
